repos:
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.2'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
